'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { id } = require('ethers');
const { setup } = require('./helpers/aggregate');
test('required two-source accounting scenario: missing coverage, epoch1 denial, repayment, epoch2 reservation and stale competitor',async()=>{
  const s=await setup(); s.vm.setTimestamp(1000);
  await s.gate.write('setPolicy',[60_000_000n]);
  await s.open(0,30_000_000n);
  const bOpen=await s.sources[1].write('openLoan',[id('loan-1'),require('./helpers/aggregate').BORROWER,require('./helpers/aggregate').OWNER,id('asset'),20_000_000n]);
  for(const source of s.sources) await source.write('seal',[]);
  await s.checkpoint(0);
  const bCp=await s.sources[1].write('checkpoint',[]);
  await assert.rejects(()=>s.ledger.write('finalizeSnapshot',[1]),/CoverageIncomplete/);
  await assert.rejects(async()=>s.gate.write('reserve',await s.reserveArgs('missing',20_000_000n)),/DecisionDenied\(2\)/);
  await s.submit(1,bOpen); await s.submit(1,bCp); await s.ledger.write('finalizeSnapshot',[1]);
  assert.equal(await s.ledger.readOne('totalDebt'),50_000_000n);
  assert.equal((await s.gate.readOne('evaluate',[20_000_000n])).reason,1n);
  await s.submit(1,await s.sources[1].write('repay',[id('loan-1'),10_000_000n]));
  assert.equal(await s.ledger.readOne('totalDebt'),40_000_000n);
  assert.equal(await s.ledger.readOne('snapshotComplete'),false);
  for(let i=0;i<2;i++) await s.checkpoint(i);
  await s.ledger.write('finalizeSnapshot',[2]);
  const args=await s.reserveArgs('winner',20_000_000n);
  assert.equal((await s.gate.readOne('evaluate',[20_000_000n])).allowed,true);
  await s.gate.write('reserve',args);
  await assert.rejects(()=>s.gate.write('reserve',[id('competitor'),...args.slice(1)]),/StaleStateVersion/);
  const d=await s.gate.readOne('evaluate',[1_000_000n]);
  assert.equal(d.reservedCredit,20_000_000n); assert.equal(d.headroom,0n); assert.equal(d.reason,1n);
});
